version: '2'

services:
  edge:
    image: thallosaurus.de/cyberpsych0siis/traefik:main
    command:
      - --pilot.token=$TRAEFIK_PILOT
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./acme.json:/acme.json"
    networks:
      - vm
      - frontend

  authserver:
    container_name: authserver
    image: thallosaurus.de/cyberpsych0siis/authserver:main
    networks:
      - frontend

  loginui:
    container_name: loginui
    image: thallosaurus.de/cyberpsych0siis/logon-ui:main
    networks:
      - frontend

  httpcats:
    container_name: errorpages-cats
    image: thallosaurus.de/cyberpsych0siis/traefik-http-cats:main
    networks:
      - frontend

  frontpage:
    container_name: frontpage
    image: thallosaurus.de/cyberpsych0siis/frontpage:main
    networks:
      - frontend

  userarea:
    container_name: userarea
    image: thallosaurus.de/cyberpsych0siis/userarea:main
    networks:
      - frontend

  vmhost:
    restart: unless-stopped
    container_name: vmhost
    image: thallosaurus.de/cyberpsych0siis/dockervm:main
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "SUBDOMAIN=rillo5000.com"
      - "NETWORK_ID=$NETWORK_ID"
#      - "BOOTSTRAP=/opt/code-server --port 8080 --host 0.0.0.0 --base-path $ENDPOINT_BASE_URI"
    networks:
      - frontend

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    command: --http-api-update --debug
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken_changeme
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "42069:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.docker/config.json:/config.json"

networks:
  vm:
    external: true
  frontend:
