version: '2'

services:
  edge:
    #image: thallosaurus.de/cyberpsych0siis/traefik:main
    image: traefik:v2.6
    command:
      - --pilot.token=$TRAEFIK_PILOT
      - --entryPoints.web.address=$TRAEFIK_HTTP_LISTEN_HOST:$TRAEFIK_HTTP_LISTEN_PORT
      - --entryPoints.web.forwardedHeaders.insecure=true
      - --entryPoints.websecure.address=$TRAEFIK_HTTPS_LISTEN_HOST:$TRAEFIK_HTTPS_LISTEN_PORT
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker
    labels:
      - "traefik.http.middlewares.auth.forwardauth.address=$AUTH_ENDPOINT"
      - "traefik.http.middlewares.auth.forwardauth.authResponseHeaders=Cookie, X-Session"
      - "traefik.http.middlewares.auth.forwardauth.authRequestHeaders=Accept, Cookie, Authorization, Location"
      - "traefik.http.middlewares.target_is_static.stripprefix.prefixes=/login,/user,/vm"
      - "traefik.http.middlewares.auth_then_strip.chain.middlewares=auth,target_is_static"
      - "traefik.http.middlewares.vscode-uuid-strip.stripprefixregex.regex=/[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./acme.json:/acme.json"
    networks:
      - vm
      - frontend

  authserver:
    container_name: authserver
    image: thallosaurus.de/cyberpsych0siis/authserver:dev
    labels:
      - traefik.http.routers.login.middlewares=errorcats@docker
    networks:
      - frontend

  loginui:
    container_name: loginui
    image: thallosaurus.de/cyberpsych0siis/logon-ui:main
    networks:
      - frontend

  httpcats:
    container_name: errorpages-cats
    image: thallosaurus.de/cyberpsych0siis/traefik-http-cats:main
    labels:
      - traefik.http.routers.frontpage.middlewares=target_is_static@file,errorcats@docker
    networks:
      - frontend

  frontpage:
    container_name: frontpage
    image: thallosaurus.de/cyberpsych0siis/frontpage:main
    networks:
      - frontend

  userarea:
    container_name: userarea
    image: thallosaurus.de/cyberpsych0siis/userarea:main
    networks:
      - frontend

  vmhost:
    restart: unless-stopped
    container_name: vmhost
    image: thallosaurus.de/cyberpsych0siis/dockervm:main
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "SUBDOMAIN=rillo5000.com"
      - "NETWORK_ID=$NETWORK_ID"
#      - "BOOTSTRAP=/opt/code-server --port 8080 --host 0.0.0.0 --base-path $ENDPOINT_BASE_URI"
    networks:
      - frontend

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    command: --http-api-update --debug
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=$WATCHTOWER_HTTP_API_TOKEN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "42069:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.docker/config.json:/config.json"
      
  garbagecollector:
    container_name: gc
    image: thallosaurus.de/cyberpsych0siis/garbage-collector
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  vm:
    external: true
  frontend:
